GET http://localhost:5000/api/title

###

GET http://localhost:5000/api/title/5fb2886c1926360544f86d0d

###

POST http://localhost:5000/api/title
Content-Type: application/json

{
    "chatnumber": 5,
    "title": "test-rest-api",
    "date": "heute"
}

###
DELETE http://localhost:5000/api/title/5fb3dbad7789b3099c7b980f

###
Patch http://localhost:5000/api/title/5fb2886c1926360544f86d0d
Content-Type: application/json

{
    "date": 2020
}

###
GET http://localhost:5000/api/chats

###

POST http://localhost:5000/api/drafts
Content-Type: application/json

{
    "title": "test",
    "messages": [{
        "messagenumber": 1,
        "name": "flo",
        "content": "testnachricht",
        "time": "22:00",
        "color": 0
    },
    {
        "messagenumber": 2,
        "name": "lotti",
        "content": "wasweißich",
        "time": "22:05",
        "color": 1
    }
],
"button": [{
    "key": 1,
    "id": "hans",
    "phil": "hans"
}]
}